---
title: "Untitled"
output: html_document
date: "2025-01-27"
---

```{r}
library(tidyplots)
library(tidyverse)
```

```{r}
source('src.R')
```

### Plot P(s) curves

```{r}
# read files generated by contact_map_comparisons.ipynb file
rcmc_all_ps = set_names(celltypes) |> 
    map(~ mutate(read_tsv(paste0('comparisons_by_distance/', .x, '_rcmc_cvd_table.txt')), 
            celltype = .x)) |>
    reduce(bind_rows) |> 
    filter(!is.na(balanced.avg.smoothed.agg) & dist >= 2) |> 
    distinct(dist_bp, balanced.avg.smoothed.agg, celltype) |> 
    mutate(experiment = 'RCMC')

microc_all_ps = set_names(celltypes) |> 
    map(~ mutate(read_tsv(paste0('comparisons_by_distance/', .x, '_microc_regions_cvd_table.txt')), 
            celltype = .x)) |>
    reduce(bind_rows) |> 
    filter(!is.na(balanced.avg.smoothed.agg) & dist >= 2) |> 
    distinct(dist_bp, balanced.avg.smoothed.agg, celltype) |> 
    mutate(experiment = 'Micro-C')

harris_ps = read_tsv(paste0('comparisons_by_distance/harris_hic_regions_cvd_table.txt')) |> 
    mutate(experiment = 'Hi-C', celltype = 'GM12878') |> 
    filter(!is.na(balanced.avg.smoothed.agg) & dist >= 2) |> 
    distinct(dist_bp, balanced.avg.smoothed.agg, celltype, experiment) 
```

```{r}
bind_rows(rcmc_all_ps, microc_all_ps, harris_ps) |> 
    mutate(name = paste(celltype, experiment)) |> 
    mutate(experiment = factor(experiment, levels = c('RCMC', 'Micro-C', 'Hi-C')),
           name = factor(name, levels = c('GM12878 Micro-C', 'GM12878 RCMC', 'HCT116 Micro-C', 'HCT116 RCMC',
                                          'K562 Micro-C', 'K562 RCMC', 'H1 Micro-C', 'H1 RCMC', 'GM12878 Hi-C'))) |> 
    tidyplot(x = dist_bp, y = balanced.avg.smoothed.agg, color = name, width = 60, height = 60, linetype = experiment) |>
    add_line() |>
    adjust_x_axis(transform = 'log10', labels = scales::label_log(), guide = "axis_logticks",
                  limits = c(1E3, 3E6)) |>
    adjust_y_axis(transform = 'log10', labels = scales::label_log(), guide = "axis_logticks") |>
    adjust_colors(new_colors = c(rep(celltype_colours, each = 2), '#23344d')) |> 
    adjust_y_axis_title('contact frequency') |> 
    adjust_x_axis_title('genomic separation') 
    # save_plot('figures/ps_curves.pdf')
```

```{r}
rcmc_all_der = set_names(celltypes) |> 
    map(~ mutate(read_tsv(paste0('comparisons_by_distance/', .x, '_rcmc_der_table.txt')), 
            celltype = .x)) |> 
    reduce(bind_rows) |> 
    filter(!is.na(balanced.avg.smoothed.agg) & dist_bp > 2000) |> 
    mutate(experiment = 'RCMC')

microc_all_der = set_names(celltypes) |> 
    map(~ mutate(read_tsv(paste0('comparisons_by_distance/', .x, '_microc_der_table.txt')), 
            celltype = .x)) |> 
    reduce(bind_rows) |> 
    filter(!is.na(balanced.avg.smoothed.agg) & dist_bp > 2000) |> 
    mutate(experiment = 'Micro-C')

harris_hic_der = read_tsv('comparisons_by_distance/harris_hic_der_table.txt') |> 
    filter(!is.na(balanced.avg.smoothed.agg) & dist_bp > 2000) |> 
    mutate(experiment = 'Hi-C', celltype = 'GM12878')
```

```{r}
bind_rows(rcmc_all_der, microc_all_der, harris_hic_der) |> 
    mutate(name = paste(celltype, experiment)) |> 
    mutate(experiment = factor(experiment, levels = c('RCMC', 'Micro-C', 'Hi-C')),
           name = factor(name, levels = c('GM12878 Micro-C', 'GM12878 RCMC', 'HCT116 Micro-C', 'HCT116 RCMC',
                                          'K562 Micro-C', 'K562 RCMC', 'H1 Micro-C', 'H1 RCMC', 'GM12878 Hi-C'))) |> 
    tidyplot(x = dist_bp, y = der, color = name, width = 60, height = 20, linetype = experiment) |>
    add_line() |>
    adjust_x_axis(transform = 'log10', labels = scales::label_log(), guide = "axis_logticks",
                  limits = c(1E3, 3E6)) |>
    adjust_colors(new_colors = c(rep(celltype_colours, each = 2), '#23344d')) |> 
    adjust_y_axis_title('contact frequency') |> 
    adjust_x_axis_title('genomic separation') |> 
    save_plot('figures/der_curves.pdf')
```

### Plot fraction filled by distance 

```{r}
# files generated by contact_map_comparisons.ipynb file
read_tsv('comparisons_by_distance/RCMC_regions_all_fraction_filled_by_distance.tsv', show_col_types = FALSE) |> 
    mutate(experiment = 'RCMC') |> 
    bind_rows(read_tsv('comparisons_by_distance/microc_regions_all_fraction_filled_by_distance.tsv', show_col_types = FALSE) |> 
              mutate(experiment = 'Micro-C')) |> 
    bind_rows(read_tsv('comparisons_by_distance/harris_hic_fraction_filled_by_distance.tsv', show_col_types = FALSE) |> 
          mutate(experiment = 'Hi-C')) |> 
    mutate(experiment = factor(experiment, levels = c('RCMC', 'Micro-C', 'Hi-C')),
           clr = factor(clr, levels = celltypes)) |> 
    ggplot(aes(distance, frac_filled, shape = experiment, fill = clr, col = clr)) +
    geom_line(lty = 3) +
    geom_point(alpha = 1, col = 'NA', size = 4) +
    plot_theme() +
    scale_x_log10(guide = "axis_logticks", labels = scales::label_log()) +
    ylab('Fraction of bins with >1 read') +
    scale_shape_manual(values = c(21, 23, 22)) +
    scale_color_manual(values = c('#23344d', '#136f63', '#C64191', '#dd8c22')) +
    scale_fill_manual(values = c('#23344d', '#136f63', '#C64191', '#dd8c22')) +
    theme(legend.position = 'None')

ggsave('rcmc_microc_fraction_filled_by_distance.pdf', width = 9, height = 6)
```